[build]
  publish = "dist"
  command = "expo export -p web"

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
